openapi: 3.0.3
info:
  title: Swagger Subsidy CRM - OpenAPI 3.0
  description: |-
    Based on our design first approach, this is an API design and documentation based on the OpenAPI 3.0 specification for our Subsidy CRM Project.

    Some useful links:
    - [The Subsidy CRM repository](https://github.com/rakeshsahuinfo/subsidycrm_aws)

  contact:
    email: hello@whizzact.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Here you can find the design documentation for the application
  url: https://docs.google.com/spreadsheets/d/1z9GJmY8C16zSpZ20JRSRorU9PF_IifVHAFxGl2acfJk/edit?usp=drive_link
servers:
  - url: https://subsidycrm.swagger.io/api/v1
tags:
  - name: Customer
    description: APIs to manage Customer object
  - name: Bookings
    description: APIs to manage Bookings object for a Customer
  - name: User
    description: APIs to manage User object
  - name: Payment
    description: APIs to manage Payments and Invoices object 
  - name: Auth
    description: APIs to manage Authentication
  - name: Notification
    description: APIs to manage notifications
  - name: Enum
    description: APIs to manage Enum configurations
paths:
  /customer:
    get:
      tags:
        - Customer
      summary: Find all customers
      description: Find all customers and filter them based on the conditions provided
      operationId: getCustomers
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: false
          explode: true
          schema:
            type: string
            default: active
            enum:
              - active
              - inactive
      responses:
        '200':
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '400':
          description: Invalid status value

    post:
      tags:
        - Customer
      summary: Add a new Customer
      description: Add a new Customer to the CRM System
      operationId: addCustomer
      requestBody:
        required: true
        description: Create a new Customer in the CRM System
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Customer Successfully Added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer' 
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /customer/{customerId}:
    get:
      tags:
        - Customer
      summary: Find Customer by ID
      description: Returns a single Customer details
      operationId: getCustomerById
      parameters:
        - name: customerId
          in: path
          description: ID of Customer to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Customer not found
    put:
      tags:
        - Customer
      summary: Update an existing Customer
      description: Update an existing Customer by Id
      operationId: updateCustomer
      parameters:
        - name: customerId
          in: path
          description: ID of Customer to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update an existing Customer in the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        '200':
          description: Customer Successfully Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Invalid ID supplied
        '404':
          description: Customer not found
        '422':
          description: Validation exception
  
  /customer/{id}/booking:
    post:
      summary: Create a new booking for a customer
      tags:
        - Bookings
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the customer
      requestBody:
        description: Booking details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '201':
          description: Booking created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingResponse'
        '400':
          description: Invalid input
        '404':
          description: Customer not found
    
    get:
      summary: Get all bookings for a customer
      tags:
        - Bookings
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the customer
      responses:
        '200':
          description: List of bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookingResponse'
        '404':
          description: Customer not found 

  /booking:
    get:
      summary: Get all bookings for all customers
      tags : 
        - Bookings
      operationId: getAllBookings
      responses:
        '200':
          description: Successful response with a list of bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookingResponse'  

  /customer/{id}/booking/{id}:
    put:
      summary: Update a specific booking for a customer
      tags:
        - Bookings
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the customer
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the booking
      requestBody:
        description: Updated booking details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '200':
          description: Booking updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingResponse'
        '400':
          description: Invalid input
        '404':
          description: Booking or customer not found
    
    delete:
      summary: Delete a specific booking for a customer
      tags:
        - Bookings
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the customer
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the booking
      responses:
        '204':
          description: Booking deleted successfully
        '404':
          description: Booking or customer not found
    
    get:
      summary: Get details of a specific booking for a customer
      tags:
        - Bookings
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the customer
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the booking
      responses:
        '200':
          description: Booking details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingResponse'
        '404':
          description: Booking or customer not found

  /customer/{id}/booking/{id}/status:
    patch:
      summary: Update the status of a specific booking for a customer
      tags:
        - Bookings
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the customer
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the booking
      requestBody:
        description: Updated status
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [pending, confirmed, cancelled, completed]
      responses:
        '200':
          description: Booking status updated successfully
        '400':
          description: Invalid input
        '404':
          description: Booking or customer not found

  /customer/{id}/booking/{id}/invoice:
    get:
      summary: Get the invoice for a specific booking
      tags:
        - Bookings
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the customer
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the booking
      responses:
        '200':
          description: Booking invoice details
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoiceId:
                    type: string
                  amount:
                    type: number
                  paymentStatus:
                    type: string
                  paymentMethod:
                    type: string
        '404':
          description: Booking or customer not found


  /notification:
    get:
      tags:
        - Notification
      summary: Get all notifications
      description: Retrieve a list of all notifications.
      responses:
        '200':
          description: A list of notifications.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'

    post:
      tags:
        - Notification
      summary: Create a new notification
      description: Add a new notification.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewNotification'
      responses:
        '201':
          description: Notification successfully created.
        '400':
          description: Invalid input provided.

  /notification/{id}:
    get:
      tags:
        - Notification
      summary: Get a notification by ID
      description: Retrieve a specific notification by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the notification to retrieve.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Notification details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '404':
          description: Notification not found.

    put:
      tags:
        - Notification
      summary: Update a notification
      description: Update the details of an existing notification.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the notification to update.
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '200':
          description: Notification successfully updated.
        '400':
          description: Invalid input provided.
        '404':
          description: Notification not found.

  /enum:
    get:
      tags:
        - Enum
      summary: Get enum values by type
      description: Retrieve the enum values corresponding to the provided type.
      parameters:
        - name: type
          in: query
          required: true
          description: The type for which to retrieve enum values.
          schema:
            type: string
      responses:
        '200':
          description: A list of enum values.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ENUM'
        '400':
          description: Invalid type provided.
    post:
      tags:
        - Enum
      summary: Create a new enum value
      description: Add a new enum value to the specified type.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ENUM'
      responses:
        '201':
          description: Enum value successfully created.
        '400':
          description: Invalid input provided.
  /enum/type/{type}/id/{id}:
    get:
      tags:
        - Enum
      summary: Get an enum value by type and ID
      description: Retrieve a specific enum value based on its type and ID.
      parameters:
        - name: type
          in: path
          required: true
          description: The type of enum to retrieve.
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The ID of the enum value to retrieve.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Enum value details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ENUM'
        '404':
          description: Enum value not found.
  /enum/{id}:
    delete:
      tags:
        - Enum
      summary: Delete an enum value
      description: Delete a specific enum value by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the enum value to delete.
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Enum value successfully deleted.
        '404':
          description: Enum value not found.

  
   
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the customer
        name:
          type: string
          description: Customer's name
        email:
          type: string
          description: Customer's email address
        mobile:
          type: string
          description: Customer's mobile number
        address:
          type: string
          description: Customer's residential address
        product:
          type: integer
          description: Reference to product
        model:
          type: integer
          description: Reference to model
        varient:
          type: integer
          description: Reference to variant
        modification:
          type: integer
          description: Reference to modification
        referenceBy:
          type: string
          description: Name of the person or entity who referred the customer
        createdDate:
          type: string
          format: date-time
          description: Timestamp when the record was created
        updatedDate:
          type: string
          format: date-time
          description: Timestamp when the record was last updated
        createdBy:
          type: integer
          description: ID of the user who created the record
        updatedBy:
          type: integer
          description: ID of the user who last updated the record
      required:
        - name
        - email
        - mobile
        - address

    Notification:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the notification.
        title:
          type: string
          description: Title of the notification.
        message:
          type: string
          description: Message content of the notification.
        status:
          type: string
          description: Status of the notification (e.g., created, viewed).
          enum:
            - created
            - viewed
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the notification was created.
    NewNotification:
      type: object
      properties:
        title:
          type: string
          description: Title of the notification.
        message:
          type: string
          description: Message content of the notification.
        status:
          type: string
          description: Status of the notification.
          enum:
            - created
            - viewed
    ENUM:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the enum value.
        type:
          type: string
          description: Type of the enum.
        value:
          type: string
          description: The actual enum value.
      required:
        - type
        - value
        